# Generated by Django 4.2.1 on 2023-12-08 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
    ]
